server:
  port: 9010
spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email
    stream:
      bindings:
        email-in-0:
          destination: "send-communication"
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
  mail:
    host: smtp.gmail.com
    port: 587
    username: "inkululokeshkumar1@gmail.com"
    password: "lokesh"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


